### PR TITLE
installing deps via pipenv first

### PR DESCRIPTION
**Pull request by goern**

### CODE REVIEW

**Comment by ghost** [comment]
Build succeeded.

- [linters ](https://zuul.thoth-station.ninja/logs/12/12/636effb855fb0f53852bdd7b73b4a6cef4d6c6d3/check/linters/a16c90f/) : SUCCESS in 5m 55s

**Comment by ghost** [comment]
Build succeeded.

- [linters ](https://zuul.thoth-station.ninja/logs/12/12/a1b3bf7d5efbe25ad6365b12475cb47b2fa24964/check/linters/857f306/) : SUCCESS in 10m 52s

**Comment by goern** [comment]
recheck

**Comment by goern** [comment]
recheck

**Pull request merged**
